### ISSUE TITLE
Not compatible with get_process_mem 0.1.1

### ISSUE THREAD

**Issue by killion** [schneems/puma_auto_tune#13]
If you run with get_process_mem 0.1.1 instead of 0.0.2 the memory usage is reported incorrectly and workers constantly get added. Sorry I haven't been able to diagnose it further yet.

**Comment by borisnadion** [comment]
is it still relevant, or it's safe to use puma_auto_tune on heroku sedar-14?

**Comment by schneems** [comment]
Do not use https://github.com/schneems/puma_auto_tune/blob/master/README.md#stability
