### ISSUE TITLE
Improved stability on Heroku?

### ISSUE THREAD

**Issue by barelyknown** [schneems/puma_auto_tune#17]
I understand from the README that this should not be used in production. But, I tested the gem today on an app that has a sudden unexpected difficult-to-diagnose memory leak, and it seemed to work perfectly. Did something change with Heroku/Linux that would explain that?

I'd obviously like to just find the memory leak, but this seems to be an effective option right now.

<img width="840" alt="tts-sourcing-production_ _metrics___heroku" src="https://cloud.githubusercontent.com/assets/693652/11550844/a5569fe8-9941-11e5-9980-751031af12f2.png">

**Comment by schneems** [comment]
I put that warning as more of a CYA. It __may__ work, but it's kinda surprising when it does. The core issue hasn't been fixed (that memory measurement on Heroku is inherently flawed and different from what the actual container is seeing). I would recommend http://github.com/schneems/puma_worker_killer with rolling restarts for more consistent behavior. Maybe we should put that in the README

**Comment by barelyknown** [comment]
I'm going to see how it goes for a couple of days to see if there are inconsistencies and then switch to puma_worker_killer if there are. But so far, so good.
