### ISSUE TITLE
Memory usage probably wrong

### ISSUE THREAD

**Issue by MarceloCajueiro** [schneems/puma_auto_tune#6]
Hey guys,

I'm using puma auto tune in an api with heroku and it looks that auto tune is seeing the wrong amount of used memory.

Here's a librato chart with the date:

![correlate___librato](https://cloud.githubusercontent.com/assets/26076/2592736/92e9652e-ba78-11e3-96fd-e43ffc1f59ed.png)

The current configuration is:

``` ruby
PumaAutoTune.config do |config|
  config.ram = 1024 # 2x dynos
end

PumaAutoTune.start
```

The app is using only one thread.

Is this right?

Thanks!

**Comment by grosser** [comment]
could this help ? 
heroku labs:enable log-runtime-metrics --app YOUR_APP_NAME

**Comment by schneems** [comment]
whacamole is pretty cool concept, have you tried it? I'm not in love with requiring people to embed an API token in their app, stuff like that is a bit messy ATM. Maybe we should link people to that from the readme?

**Comment by grosser** [comment]
Did not try it, using `restart every 2 hours` now :D
http://stackoverflow.com/questions/8986259/restart-my-heroku-application-automatically/33943132#33943132


But adding it to the readme sounds like a good idea ... lot's of desperate
people coming her ...
